pcm.dsnoop_rx_all {
    type dsnoop
    ipc_key 3000
    slave {
        pcm "hw:CARD=Audio,DEV=0"
        channels 2
        rate 48000
    }
}

pcm.route_rx1 {
    type route
    slave.pcm "dsnoop_rx_all"
    slave.channels 2
    ttable.0.1 1
}

pcm.route_rx2 {
    type route
    slave.pcm "dsnoop_rx_all"
    slave.channels 2
    ttable.0.0 1
}

pcm.rx1 {
    type plug
    slave.pcm "route_rx1"
}

pcm.rx2 {
    type plug
    slave.pcm "route_rx2"
}

pcm.dmix_tx_all {
    type dmix
    ipc_key 4000
    slave {
        pcm "hw:CARD=Audio,DEV=0"
        channels 2
        rate 48000
    }
}

pcm.route_tx1 {
    type route
    slave.pcm "dmix_tx_all"
    slave.channels 2
    ttable.0.1 1
}

pcm.route_tx2 {
    type route
    slave.pcm "dmix_tx_all"
    slave.channels 2
    ttable.0.0 1
}

pcm.tx1 {
    type plug
    slave.pcm "route_tx1"
}

pcm.tx2 {
    type plug
    slave.pcm "route_tx2"
}